DROP TABLE DETALLE_RECETA CASCADE CONSTRAINTS;
DROP TABLE PAGO CASCADE CONSTRAINTS;
DROP TABLE RECETA CASCADE CONSTRAINTS;
DROP TABLE MEDICAMENTO CASCADE CONSTRAINTS;
DROP TABLE TIPO_MEDICAMENTO CASCADE CONSTRAINTS;
DROP TABLE TIPO_RECETA CASCADE CONSTRAINTS;
DROP TABLE PACIENTE CASCADE CONSTRAINTS;
DROP TABLE MEDICO CASCADE CONSTRAINTS;
DROP TABLE DIGITADOR CASCADE CONSTRAINTS;
DROP TABLE ESPECIALIDAD CASCADE CONSTRAINTS;
DROP TABLE COMUNA CASCADE CONSTRAINTS;
DROP TABLE REGION CASCADE CONSTRAINTS;

-- Parte 1

CREATE TABLE REGION (
    id_region NUMBER(2) NOT NULL,
    nombre VARCHAR2(50) NOT NULL
);

ALTER TABLE REGION ADD CONSTRAINT region_pk PRIMARY KEY (id_region);

CREATE TABLE COMUNA (
    id_comuna NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 1101 INCREMENT BY 1) NOT NULL,
    nombre VARCHAR2(50) NOT NULL,
    id_region NUMBER(2) NOT NULL
);

ALTER TABLE COMUNA ADD CONSTRAINT comuna_pk PRIMARY KEY (id_comuna);

ALTER TABLE COMUNA ADD CONSTRAINT comuna_region_fk 
    FOREIGN KEY (id_region) REFERENCES REGION(id_region);

CREATE TABLE ESPECIALIDAD (
    id_especialidad NUMBER GENERATED ALWAYS AS IDENTITY NOT NULL,
    nombre VARCHAR2(100) NOT NULL
);

ALTER TABLE ESPECIALIDAD ADD CONSTRAINT especialidad_pk PRIMARY KEY (id_especialidad);

CREATE TABLE TIPO_RECETA (
    id_tipo_receta NUMBER NOT NULL,
    nombre VARCHAR2(50) NOT NULL
);

ALTER TABLE TIPO_RECETA ADD CONSTRAINT tipo_receta_pk PRIMARY KEY (id_tipo_receta);

CREATE TABLE TIPO_MEDICAMENTO (
    id_tipo_medicamento NUMBER NOT NULL,
    nombre VARCHAR2(50) NOT NULL
);

ALTER TABLE TIPO_MEDICAMENTO ADD CONSTRAINT tipo_medicamento_pk PRIMARY KEY (id_tipo_medicamento);

CREATE TABLE DIGITADOR (
    rut NUMBER(8) NOT NULL,
    dv VARCHAR2(1) NOT NULL,
    nombre VARCHAR2(100) NOT NULL,
    apellido VARCHAR2(100) NOT NULL,
    telefono VARCHAR2(15),
    email VARCHAR2(100)
);

ALTER TABLE DIGITADOR ADD CONSTRAINT digitador_pk PRIMARY KEY (rut);

ALTER TABLE DIGITADOR ADD CONSTRAINT digitador_dv_check 
    CHECK (dv IN ('0','1','2','3','4','5','6','7','8','9','K'));

CREATE TABLE MEDICO (
    rut NUMBER(8) NOT NULL,
    dv VARCHAR2(1) NOT NULL,
    nombre VARCHAR2(100) NOT NULL,
    apellido VARCHAR2(100) NOT NULL,
    telefono VARCHAR2(15) NOT NULL,
    email VARCHAR2(100),
    id_especialidad NUMBER NOT NULL
);

ALTER TABLE MEDICO ADD CONSTRAINT medico_pk PRIMARY KEY (rut);

ALTER TABLE MEDICO ADD CONSTRAINT medico_dv_check 
    CHECK (dv IN ('0','1','2','3','4','5','6','7','8','9','K'));

ALTER TABLE MEDICO ADD CONSTRAINT medico_telefono_unique UNIQUE (telefono);

ALTER TABLE MEDICO ADD CONSTRAINT medico_especialidad_fk 
    FOREIGN KEY (id_especialidad) REFERENCES ESPECIALIDAD(id_especialidad);

CREATE TABLE PACIENTE (
    rut NUMBER(8) NOT NULL,
    dv VARCHAR2(1) NOT NULL,
    nombre VARCHAR2(100) NOT NULL,
    apellido VARCHAR2(100) NOT NULL,
    direccion VARCHAR2(200) NOT NULL,
    telefono VARCHAR2(15),
    email VARCHAR2(100),
    edad NUMBER(3),
    id_comuna NUMBER NOT NULL
);

ALTER TABLE PACIENTE ADD CONSTRAINT paciente_pk PRIMARY KEY (rut);

ALTER TABLE PACIENTE ADD CONSTRAINT paciente_dv_check 
    CHECK (dv IN ('0','1','2','3','4','5','6','7','8','9','K'));

ALTER TABLE PACIENTE ADD CONSTRAINT paciente_comuna_fk 
    FOREIGN KEY (id_comuna) REFERENCES COMUNA(id_comuna);

CREATE TABLE MEDICAMENTO (
    id_medicamento NUMBER NOT NULL,
    nombre VARCHAR2(200) NOT NULL,
    dosis VARCHAR2(100) NOT NULL,
    stock NUMBER(10) DEFAULT 0,
    id_tipo_medicamento NUMBER NOT NULL
);

ALTER TABLE MEDICAMENTO ADD CONSTRAINT medicamento_pk PRIMARY KEY (id_medicamento);

ALTER TABLE MEDICAMENTO ADD CONSTRAINT medicamento_stock_check CHECK (stock >= 0);

ALTER TABLE MEDICAMENTO ADD CONSTRAINT medicamento_tipo_fk 
    FOREIGN KEY (id_tipo_medicamento) REFERENCES TIPO_MEDICAMENTO(id_tipo_medicamento);

CREATE TABLE RECETA (
    id_receta NUMBER NOT NULL,
    fecha_emision DATE DEFAULT SYSDATE NOT NULL,
    fecha_expiracion DATE,
    observaciones VARCHAR2(500),
    diagnostico VARCHAR2(300) NOT NULL,
    rut_paciente NUMBER(8) NOT NULL,
    rut_medico NUMBER(8) NOT NULL,
    rut_digitador NUMBER(8) NOT NULL,
    id_tipo_receta NUMBER NOT NULL
);

ALTER TABLE RECETA ADD CONSTRAINT receta_pk PRIMARY KEY (id_receta);

ALTER TABLE RECETA ADD CONSTRAINT receta_fecha_check 
    CHECK (fecha_expiracion IS NULL OR fecha_expiracion >= fecha_emision);

ALTER TABLE RECETA ADD CONSTRAINT receta_paciente_fk 
    FOREIGN KEY (rut_paciente) REFERENCES PACIENTE(rut);

ALTER TABLE RECETA ADD CONSTRAINT receta_medico_fk 
    FOREIGN KEY (rut_medico) REFERENCES MEDICO(rut);

ALTER TABLE RECETA ADD CONSTRAINT receta_digitador_fk 
    FOREIGN KEY (rut_digitador) REFERENCES DIGITADOR(rut);

ALTER TABLE RECETA ADD CONSTRAINT receta_tipo_fk 
    FOREIGN KEY (id_tipo_receta) REFERENCES TIPO_RECETA(id_tipo_receta);

CREATE TABLE DETALLE_RECETA (
    id_receta NUMBER NOT NULL,
    id_medicamento NUMBER NOT NULL,
    cantidad NUMBER(5) NOT NULL,
    instrucciones VARCHAR2(300)
);

ALTER TABLE DETALLE_RECETA ADD CONSTRAINT detalle_receta_pk 
    PRIMARY KEY (id_receta, id_medicamento);

ALTER TABLE DETALLE_RECETA ADD CONSTRAINT detalle_cantidad_check CHECK (cantidad > 0);

ALTER TABLE DETALLE_RECETA ADD CONSTRAINT detalle_receta_fk 
    FOREIGN KEY (id_receta) REFERENCES RECETA(id_receta);

ALTER TABLE DETALLE_RECETA ADD CONSTRAINT detalle_medicamento_fk 
    FOREIGN KEY (id_medicamento) REFERENCES MEDICAMENTO(id_medicamento);

CREATE TABLE PAGO (
    id_pago NUMBER NOT NULL,
    monto NUMBER(10,2) NOT NULL,
    fecha_pago DATE DEFAULT SYSDATE NOT NULL,
    metodo_pago VARCHAR2(20) NOT NULL,
    id_receta NUMBER NOT NULL
);

ALTER TABLE PAGO ADD CONSTRAINT pago_pk PRIMARY KEY (id_pago);

ALTER TABLE PAGO ADD CONSTRAINT pago_monto_check CHECK (monto > 0);

ALTER TABLE PAGO ADD CONSTRAINT pago_receta_fk 
    FOREIGN KEY (id_receta) REFERENCES RECETA(id_receta);


-- Parte 2

ALTER TABLE MEDICAMENTO ADD precio_unitario NUMBER(10,2);

ALTER TABLE MEDICAMENTO ADD CONSTRAINT medicamento_precio_check 
    CHECK (precio_unitario BETWEEN 1000 AND 2000000);

ALTER TABLE PAGO ADD CONSTRAINT pago_metodo_check 
    CHECK (metodo_pago IN ('EFECTIVO', 'TARJETA', 'TRANSFERENCIA'));

ALTER TABLE PACIENTE DROP COLUMN edad;

ALTER TABLE PACIENTE ADD fecha_nacimiento DATE;